# https://alacritty.org/config-alacritty.html

# environment variables
env.TERM = "xterm-256color"

 # directory to start in (when "None" use parent directory)
working_directory = "None"

[window]
dimensions = { columns = 280, lines = 80}
# window startup position, if none wm will handle
position = "None"
padding = { x = 15, y = 15}
# spread additional padding around terminal
dynamic_padding = false
decorations = "buttonless"
opacity = 0.97
blur = false
startup_mode = "Windowed"
# Window title
title = "Alacritty"
# allow terminal applications to change window title
dynamic_title = true
# override variant of system system theme (when "None" use system default)
decorations_theme_variant = "None"
# resize window by discrete steps equal to cell dimensions.
resize_increments = false
# make Option key behave as Alt.
option_as_alt = "Both"

[scrolling]
# maximum number of lines in the scrollback buffer (0 to disable)
history = 100000
multiplier = 3

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic"}
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic"}
size = 15
# extra space around each character (i.e x is line spacing and y is letter spacing)
offset = { x = 0, y = 0}
glyph_offset = { x = 0, y = 0}
builtin_box_drawing = false

# colours are kept default

[bell]
# visual bell animation effect for flashing the screen when the visual bell is rung
animation = "Linear"
# duration of visual bell flash in ms
duration = 0
color = "#ffffff"
# program to execute whenever bell is rung
command = "None"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
# when true, selected text will be copied to the primary clipboard.
save_to_clipboard = true

[cursor]
style.shape = "Block"
style.blinking = "Off"
# leave vi mode to seperate config
vi_mode_style = "None"
# cursor blinking interval
blink_interval = 750
blink_timeout = 0
# when this is true, the cursor will be rendered as a hollow box when the window is not focused
unfocused_hollow = true
thickness = 0.15

[terminal]
# write to the system clipboard using osc52 escape sequence
osc52 = "OnlyCopy"

[mouse]
hide_when_typing = false
bindings = []

[keyboard]
bindings = []

[general]
live_config_reload = true

 # directory to start in (when "None" use parent directory)
working_directory = "None"
ipc_socket = false
# https://alacritty.org/config-alacritty.html

# import additional configuration
import = [] 
