tap 'homebrew/cask-fonts'

# more recent versions of some macOS tools
brew 'grep'
brew 'zsh'

# essential packages
brew 'stow'
brew 'ripgrep'
brew 'bat'
brew 'git'
brew 'zplug'
brew 'neovim'
brew 'python3'
brew 'yarn'
brew 'nvm'
brew 'lazygit'
brew 'tmux'
brew 'lsd'
brew 'tree'
brew 'git-delta'
brew 'zoxide'
brew 'stylua'
brew 'lf'
brew 'fd'
brew 'fzf'

# applications
cask 'google-chrome'
cask 'slack'
cask 'spotify'
cask 'raycast'
cask 'appcleaner'
cask 'karabiner-elements'
cask 'alt-tab'

# fonts
cask 'font-hack-nerd-font'
cask 'font-meslo-lg-nerd-font'
